#**Step1: Import the libraries**

In [1]:
#Importing libraries
import numpy as np      
import pandas as pd

Mounted at /drive

#**Step2: Import the dataset**

In [2]:
path = '/drive/MyDrive/Colab Notebooks/boston_pre.csv'
df = pd.read_csv(path)

#**Step3: Taking care of missing data**

In [4]:
df.isnull().sum()

CRIM         3
ZN           1
INDUS       14
CHAS         2
NOX          5
RM           6
AGE          8
DIS          4
RAD          9
TAX          6
PTRATIO      4
B            5
LSTAT        2
PRICE        1
PRICE2     506
dtype: int64

In [7]:
df1 = df.dropna(how='all')
df1 = df1.drop(['PRICE2'], axis = 1)
df1

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [9]:
df1.isnull().sum()

CRIM        2
ZN          0
INDUS      13
CHAS        1
NOX         4
RM          5
AGE         7
DIS         3
RAD         8
TAX         5
PTRATIO     3
B           4
LSTAT       1
PRICE       0
dtype: int64

#**Step4: Imputing missing values**

In [15]:
#Importing the class callwed SimpleImputer from impute model in sklearn
from sklearn.impute import SimpleImputer

#To replace the missing value we create below object of SimpleImputer class\
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df1.iloc[:, 0:13])

#Replacing the missing value using transform method
df1.iloc[:,0:13] = imputer.transform(df1.iloc[:,0:13])

In [16]:
df1.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
PRICE      0
dtype: int64